ENV["GYM_OUTPUT_DIRECTORY"] = "./fastlane/outputs/"
ENV["ACK_INHOUSE_MATCH_GIT"] = "git@gitlab.ack.ee:Ackee/ios-inhouse-certificates.git"
ENV["MATCH_GIT_URL"] = ENV["ACK_INHOUSE_MATCH_GIT"] # Default git is set to inhouse
ENV["MATCH_TYPE"] = "development" #Default match type
ENV["MATCH_DEFAULT_TEAM_ID"] = "PXDF48X6VX" #Team ID that is saved in the master branch in the inhouse repository

ENV["XCODE_VERSION"] = "~> 9.2"

INHOUSE_APPLE_ID = "unicorn@ackee.cz"
PRODUCTION_TEAM_ID = "3SMVP6VZP8" # string identifier
PRODUCTION_TEAM_ID2 = "1588142" # number identifier, anyone idea for better name?
HOCKEY_APP_ID = ""

before_all do |lane|
    if lane == :beta || lane == :release then
        xcversion(version: ENV["XCODE_VERSION"])
    end
end

lane :cart do
    sh "cd ..; carthage bootstrap --platform iOS --cache-builds; cd -"
end

lane :pods do
    sh "pod install || pod install --repo-update"
end

lane :dependencies do
    cart
    pods
end

lane :provisioning do |options|
    CONFIGURATION = options[:configuration] || UI.select("Select configuration: ", ["Debug", "AdHoc", "AppStore"])

    if CONFIGURATION == "Debug" then
        provisioning_match(configuration: CONFIGURATION, type: "development", app_identifier: [app_identifier(CONFIGURATION), app_identifier("AdHoc")],
                            username: INHOUSE_APPLE_ID, team_id: team_id(CONFIGURATION), readonly: true)
    elsif CONFIGURATION == "AdHoc" then
        provisioning_match(configuration: CONFIGURATION, type: "enterprise", app_identifier: app_identifier(CONFIGURATION),
                            username: INHOUSE_APPLE_ID, team_id: team_id(CONFIGURATION), readonly: true)
    elsif CONFIGURATION == "AppStore" then
        provisioning_match(configuration: CONFIGURATION, type: "appstore", app_identifier: app_identifier(CONFIGURATION),
                            username: dev_portal_apple_id(), team_id: PRODUCTION_TEAM_ID, readonly: true)
    end
end

lane :beta do
    SCHEME = "Stage"
    CONFIGURATION = "AdHoc"
    TARGET_RESOURCES = "../Skeleton/Resources/Images.xcassets/"

    if is_ci then
        provisioning(configuration: CONFIGURATION)
    else
        UI.message("Running locally, not running :provisioning lane, if needed run manually")
    end

    begin
        add_badge(shield: "#{get_version_string()}-#{number_of_commits}-blue", dark: true, shield_no_resize: false)
    rescue
        UI.error("Unable to add badges to app icon")
        # Put badge back to original
        sh "git checkout -- #{TARGET_RESOURCES}"
    end

    sh "git checkout -- #{TARGET_RESOURCES}"

    gym(scheme: SCHEME,
        configuration: CONFIGURATION,
        clean: false,
        export_options: {
            method: "enterprise",
            provisioningProfiles: provisioning_mapping()
        }
    )

    if !is_ci
        hockey(public_identifier: HOCKEY_APP_ID, notify: '0' )
    end
end

lane :test do |options|
    TYPE = options[:type] || UI.select("Select test type: ", ["ui", "unit"])

    if TYPE == "ui" then
        scan(scheme: "UITests", clean: false)
    elsif TYPE == "unit"
        scan(scheme: "Development", clean: false)
    end
end

lane :release do
    SCHEME = "Production"
    CONFIGURATION = "AppStore"

    if is_ci then
        provisioning(configuration: CONFIGURATION)
    else
        UI.message("Running locally, not running :provisioning lane, if needed run manually")
    end

    gym(scheme: SCHEME,
        configuration: CONFIGURATION,
        clean: true,
        export_options: {
            method: "app-store",
            provisioningProfiles: provisioning_mapping()
        }
    )

    testflight(username: itc_apple_id,
                dev_portal_team_id: PRODUCTION_TEAM_ID,
                skip_submission: true,
                skip_waiting_for_build_processing: true)
end

def provisioning_mapping()
    return nil
end

def git_user_email()
    return `git config user.email`
end

def itc_apple_id()
    return git_user_email()
end

def dev_portal_apple_id()
    return git_user_email()
end

def app_identifier(configuration)
    get_build_settings(key: "PRODUCT_BUNDLE_IDENTIFIER", build_configuration: configuration)
end

def team_id(configuration)
    get_build_settings(key: "DEVELOPMENT_TEAM", build_configuration: configuration)
end

def get_version_string
    return get_build_settings(key: "ACK_PROJECT_VERSION", build_configuration: "AppStore")
end
