INHOUSE_APPLE_ID = "unicorn@ackee.cz"
PRODUCTION_TEAM_ID = "3SMVP6VZP8" # string identifier
PRODUCTION_TEAM_ID2 = "1588142" # number identifier, anyone idea for better name?
HOCKEY_APP_ID = ""

import(download_from_git(url: "git@gitlab.ack.ee:Ackee/fastlane.git", branch: "new_start"))
